name: Publish
# Adapted from https://github.com/sbt/sbt-ci-release/blob/main/.github/workflows/release.yml

on:
  push:
    branches: [ master ]
    tags: [ "*" ]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13

      - name: Generate reports
        run: sbt coverage test coverageReport coverageAggregate makeSite

      - name: Publish coverage reports
        run: curl -s https://codecov.io/bash | bash

      - name: Publish Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/site

      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
