# Adapted from https://github.com/sbt/sbt-ci-release/blob/main/.github/workflows/release.yml
name: Publish

on:
  push:
    branches: [master]
    tags: ["*"]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13

      - name: Generate reports
        run: sbt coverage test coverageReport coverageAggregate makeSite

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3

      - name: Publish Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/site

      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
