name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8, 11, 17 ] # Include only LTS Java versions in matrix: https://www.oracle.com/java/technologies/java-se-support-roadmap.html
        scala: [ 2.11.12, 2.12.13, 2.13.5, 3.2.0 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java}}
          cache: sbt

      - name: Run tests on Scala ${{matrix.scala}}
        run: sbt ++${{matrix.scala}} clean test

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Build artifacts
        run: |
          sbt coverage test
          sbt coverageReport coverageAggregate makeSite
          curl -s https://codecov.io/bash | bash

      - name: Publish Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/site

      - name: Release
        run: sbt ci-release
